<?xml version="1.0" encoding="utf-8" ?>

<!--<!DOCTYPE mensaje [

        <!ELEMENT mensaje (remite, destinatario, asunto, texto) >
        <!ELEMENT remite (nombre, email) >
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT email (#PCDATA) >
        <!ELEMENT destinatario (nombre, email) >
        <!ELEMENT asunto (#PCDATA) >
        <!ELEMENT texto (parrafo*) >
        <!ELEMENT parrafo (#PCDATA) >

        ]>
 -->


<!DOCTYPE mensaje SYSTEM "Ele_actividad2.dtd">

    <mensaje>
        <remite>
            <nombre>Alfredo Reino</nombre>
            <email>alf@ibium.com</email>
        </remite>
        <destinatario>
            <nombre>Bill Clinton</nombre>
            <email>presindent@whitehouse.gov</email>
        </destinatario>
        <asunto>Hola Bill</asunto>

        <texto >
            <parrafo>Â¿Hola Que tal?</parrafo>
            <parrafo>Hace mucho tiempo que no escribes. A ver si llamas y quedamos pronto.</parrafo>
            <parrafo>Un saludo.</parrafo>
        </texto>

    </mensaje>