=== Alex-Jojo/XML_Basico/src/Ticket-Empresa.dtd
<!ELEMENT Invoice (Business|Image|BillTo|ShipTo|InvoiceDetails|Information|CustomerMessage|Payment)*>
<!ELEMENT Business (Name|Street|geolocation|Phone|Email|Website)*>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Street (#PCDATA)>
<!ELEMENT geolocation (#PCDATA)>
<!ELEMENT Phone (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Website (#PCDATA)>
<!ELEMENT Image (#PCDATA)>
<!ELEMENT BillTo (Name|StreetAdress|geolocation)*>
<!ELEMENT StreetAdress (#PCDATA)>
<!ELEMENT ShipTo (Name|StreetAdress|geolocation)*>
<!ELEMENT InvoiceDetails (Number|Date|TermsofPayment|geolocation)*>
<!ELEMENT Number (#PCDATA)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT TermsofPayment (#PCDATA)>
<!ELEMENT Information (Product|Description|Qty_Hrs|Rate|Amount)*>
<!ELEMENT Product (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT Qty_Hrs (#PCDATA)>
<!ELEMENT Rate (#PCDATA)>
<!ELEMENT Amount (#PCDATA)>
<!ELEMENT CustomerMessage (#PCDATA)>
<!ELEMENT Payment (Subtotal|SalesTax|Shipping|Total)*>
<!ELEMENT Subtotal (#PCDATA)>
<!ELEMENT SalesTax (#PCDATA)>
<!ELEMENT Shipping (#PCDATA)>
<!ELEMENT Total (#PCDATA)>

=== Alex-Jojo/XML_Basico/src/Actividad7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Invoice SYSTEM "Ticket-Empresa.dtd">
<Invoice>
    <Business>
        <Name>Empresa</Name>
        <Street>ubicacion</Street>
        <geolocation>Hermosillo, Sonora. 12345</geolocation>
        <Phone>111-111-1111</Phone>
        <Email>info@info.com</Email>
        <Website>www.website.com</Website>
    </Business>
    <Image>logo.jpg</Image>
    <BillTo>
        <Name>pedro</Name>
        <StreetAdress>calle</StreetAdress>
        <geolocation>Hermosillo, Sonora. 12344</geolocation>
    </BillTo>
    <ShipTo>
        <Name>pedro</Name>
        <StreetAdress>otra calle</StreetAdress>
        <geolocation>Hermosillo, Sonora. 12344</geolocation>
    </ShipTo>
    <InvoiceDetails>
        <Number>1231234</Number>
        <Date>12-12-2023</Date>
        <TermsofPayment>pagar hasta 15-12-2023</TermsofPayment>
        <geolocation>Hermosillo, Sonora. 12345</geolocation>
    </InvoiceDetails>
    <Information>
        <Product>Soda</Product>
        <Description>El mejor producto</Description>
        <Qty_Hrs>0</Qty_Hrs>
        <Rate>3</Rate>
        <Amount>12</Amount>
    </Information>
    <CustomerMessage>Hola amigo.</CustomerMessage>
    <Payment>
        <Subtotal>30</Subtotal>
        <SalesTax>20</SalesTax>
        <Shipping>10</Shipping>
        <Total>60</Total>
    </Payment>
</Invoice>
