=== Alex-Jojo/XML_Basico/src/TiposArboles.dtd
<!ELEMENT Arboles (Arbol)*>
        <!ELEMENT Arbol (Tipo|Nombrecomun|Vegetacion|Altura|FormaEstructura|ColorPrimavera|ResistenciaHeladas|ColorOtono)*>
        <!ELEMENT Tipo (#PCDATA)>
        <!ELEMENT Nombrecomun (#PCDATA)>
        <!ELEMENT Vegetacion (#PCDATA)>
        <!ELEMENT Altura (#PCDATA)>
        <!ELEMENT FormaEstructura (#PCDATA)>
        <!ELEMENT ColorPrimavera (#PCDATA)>
        <!ELEMENT ResistenciaHeladas (#PCDATA)>
        <!ELEMENT ColorOtono (#PCDATA)>

=== Alex-Jojo/XML_Basico/src/Actividad5.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Arboles SYSTEM "TiposArboles.dtd">

<Arboles>
    <Arbol>
        <Tipo>Acer monspessulanum</Tipo>
        <Nombrecomun>Arce de Montpellier, Arce menor</Nombrecomun>
        <Vegetacion>Caducifolio</Vegetacion>
        <Altura>De 6 a 10 metros</Altura>
        <FormaEstructura>Copa esférica. Tronco principal recto con bifurcaciones. Ramaje colgante</FormaEstructura>
        <ColorPrimavera>Haz verde brillante, envés verde blanquecino</ColorPrimavera>
        <ResistenciaHeladas>Heladas fuertes (hasta -15ºC)</ResistenciaHeladas>
    </Arbol>
    <Arbol>
        <Tipo>Olea europea</Tipo>
        <Nombrecomun>Olivo</Nombrecomun>
        <Vegetacion>Perenne</Vegetacion>
        <Altura>De 8 a 15 metros</Altura>
        <FormaEstructura>Copa irregular. Tronco principal irregular con bifurcaciones.</FormaEstructura>
    </Arbol>
    <Arbol>
        <Tipo>Ramaje tortuoso</Tipo>
        <ColorPrimavera>Haz verde oscuro, envés verde plateado</ColorPrimavera>
        <ResistenciaHeladas>Heladas medias (hasta -10ºC)</ResistenciaHeladas>
    </Arbol>
    <Arbol>
        <Tipo>Platanus orientalis</Tipo>
        <Nombrecomun>Platano</Nombrecomun>
        <Vegetacion>Caducifolio</Vegetacion>
        <Altura>De 20 a 25 metros</Altura>
        <FormaEstructura>Copa ovoidal. Tronco principal recto. Ramaje expandido</FormaEstructura>
        <ColorPrimavera>Haz verde medio, enves verde claro</ColorPrimavera>
        <ColorOtono>Ocre</ColorOtono>
        <ResistenciaHeladas>Heladas fuertes (hasta -20ºC)</ResistenciaHeladas>
    </Arbol>
    <Arbol>
        <Tipo>Quercus ilex</Tipo>
        <Nombrecomun>Encina</Nombrecomun>
        <Vegetacion>Perenne</Vegetacion>
        <Altura>En torno a 25 metros</Altura>
        <FormaEstructura>Copa esférica o elíptica irregular. Tronco principal recto. Ramaje tortuoso</FormaEstructura>
        <ColorPrimavera>Plateado en hojas jóvenes. En hojasantiguas, haz verde oscuro, envés plateado</ColorPrimavera>
        <ResistenciaHeladas>Heladas fuertes (hasta -15ºC)</ResistenciaHeladas>
    </Arbol>
</Arboles>
